services:
  postgres:
    image: postgres:18.3
    container_name: dbcviewer-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dbcviewer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbcviewer-postgres18-data:/var/lib/postgresql

volumes:
  dbcviewer-postgres18-data:
